///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.fabric8:kubernetes-client:6.10.0
//DEPS info.picocli:picocli:4.7.6
//MAIN CheckK8sNodeAvailability
//JAVA 21+
//DEPS ch.qos.logback:logback-classic:1.5.18


/**
 * JBang script to check Kubernetes node availability for a pending pod
 * based on taints/tolerations and memory requests vs. allocatable resources.
 * Generated by LLM (Large Language Model) for educational purposes.
 * 
 * Usage: jbang run CheckK8sNodeAvailability.java <pod> <namespace>
 */


import io.fabric8.kubernetes.api.model.*;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClientBuilder;
import io.fabric8.kubernetes.client.KubernetesClientException;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.Callable;
import java.util.logging.ConsoleHandler; // Import JUL ConsoleHandler
import java.util.logging.Formatter;     // Import JUL Formatter
import java.util.logging.Handler;       // Import JUL Handler
import java.util.logging.Level;         // Import JUL Level
import java.util.logging.LogRecord;     // Import JUL LogRecord
import java.util.logging.Logger;        // Import JUL Logger
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;


@Command(name = "CheckK8sNodeAvailability",
         mixinStandardHelpOptions = true,
         version = "CheckK8sNodeAvailability 1.11", // Increment version
         description = "Checks Kubernetes node availability for a pending pod based on taints and memory requests (JUL Logging, Plain Text).")
public class CheckK8sNodeAvailability implements Callable<Integer> {

    // Initialize Java Util Logger
    private static final Logger LOGGER = Logger.getLogger(CheckK8sNodeAvailability.class.getName());

    // Static block to configure logger for simple, unformatted console output
    static {
        // Remove default handlers from *this* logger instance if they exist
        for (Handler handler : LOGGER.getHandlers()) {
             LOGGER.removeHandler(handler);
        }
        // Add a new console handler with a simple formatter
        ConsoleHandler consoleHandler = new ConsoleHandler();
        consoleHandler.setLevel(Level.ALL); // Handle all levels
        consoleHandler.setFormatter(new SimpleConsoleFormatter());
        LOGGER.addHandler(consoleHandler);
        LOGGER.setLevel(Level.INFO); // Set the default log level for this logger
        LOGGER.setUseParentHandlers(false); // Don't propagate to root logger handlers
    }

    /**
     * Simple Formatter to just output the log message (plain text).
     */
    static class SimpleConsoleFormatter extends Formatter {
        @Override
        public String format(LogRecord record) {
            // Just return the message, add a newline character
            return formatMessage(record) + "\n";
        }
    }


    @Parameters(index = "0", description = "Name of the pending pod.")
    private String podName;

    @Parameters(index = "1", description = "Namespace of the pending pod.")
    private String namespace;

    // --- Constants for Memory Conversion ---
    private static final BigDecimal KIB_IN_BYTES = new BigDecimal("1024");
    private static final BigDecimal MIB_IN_KIB = new BigDecimal("1024");
    private static final BigDecimal GIB_IN_KIB = MIB_IN_KIB.multiply(new BigDecimal("1024"));
    private static final BigDecimal TIB_IN_KIB = GIB_IN_KIB.multiply(new BigDecimal("1024"));
    private static final BigDecimal PIB_IN_KIB = TIB_IN_KIB.multiply(new BigDecimal("1024"));
    private static final BigDecimal EIB_IN_KIB = PIB_IN_KIB.multiply(new BigDecimal("1024"));

    // Regex to extract number and optional unit from memory string
    private static final Pattern MEMORY_PATTERN = Pattern.compile("^(\\d+(\\.\\d+)?)\\s*([A-Za-z]*)$");


    // --- Helper Function: Parse Memory Units ---
    /**
     * Parses Kubernetes memory strings into Kibibytes (KiB) using Regex.
     * Returns a BigDecimal representing KiB or BigDecimal.ZERO if parsing fails.
     * Logs warnings using JUL.
     */
    public static BigDecimal parseMemoryToKib(String memStr) {
        if (memStr == null || memStr.isEmpty()) {
            return BigDecimal.ZERO;
        }
        Matcher matcher = MEMORY_PATTERN.matcher(memStr.trim());
        if (!matcher.matches()) {
            LOGGER.warning(String.format("Could not parse memory string format '%s'. Treating as 0 KiB", memStr));
            return BigDecimal.ZERO;
        }

        try {
            BigDecimal amount = new BigDecimal(matcher.group(1));
            String unit = matcher.group(3); // Unit part (e.g., "Ki", "Mi", "G", "")
            unit = (unit == null) ? "" : unit; // Ensure unit is not null

            switch (unit) {
                case "Ki": return amount;
                case "Mi": return amount.multiply(MIB_IN_KIB);
                case "Gi": return amount.multiply(GIB_IN_KIB);
                case "Ti": return amount.multiply(TIB_IN_KIB);
                case "Pi": return amount.multiply(PIB_IN_KIB);
                case "Ei": return amount.multiply(EIB_IN_KIB);
                case "k": return amount.multiply(new BigDecimal("1000")).divide(KIB_IN_BYTES, 0, RoundingMode.DOWN);
                case "M": return amount.multiply(new BigDecimal("1000000")).divide(KIB_IN_BYTES, 0, RoundingMode.DOWN);
                case "G": return amount.multiply(new BigDecimal("1000000000")).divide(KIB_IN_BYTES, 0, RoundingMode.DOWN);
                case "": return amount.divide(KIB_IN_BYTES, 0, RoundingMode.DOWN);
                default:
                    LOGGER.warning(String.format("Unrecognized memory unit '%s' in '%s'. Assuming bytes and converting to KiB.", unit, memStr));
                    return amount.divide(KIB_IN_BYTES, 0, RoundingMode.DOWN);
            }
        } catch (NumberFormatException e) {
             LOGGER.warning(String.format("Could not parse numeric value in memory string '%s'. Treating as 0 KiB", memStr));
             return BigDecimal.ZERO;
        } catch (Exception e) {
             LOGGER.log(Level.WARNING, String.format("Unexpected error parsing memory string '%s'. Treating as 0 KiB", memStr), e);
             return BigDecimal.ZERO;
        }
    }

    // --- Helper Function: Check Toleration ---
    /**
     * Checks if a given taint is tolerated by the pod's tolerations list.
     * Returns true if tolerated, false otherwise.
     */
    public static boolean checkToleration(Taint taint, List<Toleration> podTolerations) {
        if (podTolerations == null) return false;
        for (Toleration toleration : podTolerations) {
            boolean keyMatch = toleration.getKey() == null || toleration.getKey().equals(taint.getKey());
            boolean effectMatch = toleration.getEffect() == null || toleration.getEffect().equals(taint.getEffect());
            boolean operatorMatch = false;
            String operator = toleration.getOperator();
            if ("Exists".equals(operator)) {
                operatorMatch = taint.getKey() != null && (toleration.getKey() == null || toleration.getKey().equals(taint.getKey()));
            } else { // Operator is "Equal" (default)
                operatorMatch = (toleration.getValue() == null && taint.getValue() == null) ||
                                (toleration.getValue() != null && toleration.getValue().equals(taint.getValue()));
            }
            if (keyMatch && effectMatch && operatorMatch) return true;
        }
        return false;
    }


    @Override
    public Integer call() { // Main logic
        // Use JUL logger for output
        LOGGER.info(String.format("Checking scheduling prerequisites for pod '%s' in namespace '%s'...\n", podName, namespace));
        // LOGGER.info(""); // Add newline via empty log or handle in formatter

        try (KubernetesClient client = new KubernetesClientBuilder().build()) {

            // --- 1. Get Pending Pod Details ---
            Pod pod = client.pods().inNamespace(namespace).withName(podName).get();
            if (pod == null) {
                LOGGER.severe(String.format("Error: Pod '%s' not found in namespace '%s'.", podName, namespace));
                return 1;
            }

            // Calculate largest memory request
            BigDecimal podMemoryRequestKib = BigDecimal.ZERO;
            List<Container> containers = Optional.ofNullable(pod.getSpec().getContainers()).orElse(List.of());
            if (!containers.isEmpty()) {
                LOGGER.info("Pod Memory Requests per Container:");
                for (Container container : containers) {
                    String memReqStr = "N/A";
                    BigDecimal reqKib = BigDecimal.ZERO;
                    ResourceRequirements resources = container.getResources();
                    if (resources != null && resources.getRequests() != null && resources.getRequests().containsKey("memory")) {
                        Quantity memQuantity = resources.getRequests().get("memory");
                        if (memQuantity != null) {
                           memReqStr = memQuantity.toString();
                           reqKib = parseMemoryToKib(memReqStr);
                           if (reqKib.compareTo(podMemoryRequestKib) > 0) {
                               podMemoryRequestKib = reqKib;
                           }
                        } else {
                             memReqStr = "<null quantity>";
                        }
                    }
                    LOGGER.info(String.format("  - Container '%s': %s (%s KiB)", container.getName(), memReqStr, reqKib.toBigInteger()));
                }
            }

            if (podMemoryRequestKib.compareTo(BigDecimal.ZERO) == 0) {
                LOGGER.warning(String.format("%nWarning: Pod '%s' has no memory requests defined. Skipping memory checks.", podName));
            } else {
                LOGGER.info(String.format("%nPod '%s' requires %s KiB of memory (largest container request).", podName, podMemoryRequestKib.toBigInteger()));
            }

            // Get Pod Tolerations
            List<Toleration> podTolerations = Optional.ofNullable(pod.getSpec().getTolerations()).orElse(new ArrayList<>());
            LOGGER.info(String.format("Pod Tolerations: %s", podTolerations.isEmpty() ? "None" : podTolerations.stream().map(Object::toString).collect(Collectors.joining(", "))));


            // --- 2. Get All Nodes ---
            NodeList nodeList = client.nodes().list();
            List<Node> nodes = Optional.ofNullable(nodeList.getItems()).orElse(List.of());
            int totalNodes = nodes.size();
            LOGGER.info(String.format("%nFound %d nodes in the cluster.", totalNodes));

            // --- 3. Check Each Node ---
            int availableNodesCount = 0;
            List<String> rejectedByTaint = new ArrayList<>();
            List<String> rejectedByMemory = new ArrayList<>();
            List<String> nodesWithIssues = new ArrayList<>();

            LOGGER.info("\n--- Node Analysis ---");
            for (Node node : nodes) {
                String nodeName = node.getMetadata().getName();
                LOGGER.info(String.format("%nAnalyzing Node: %s", nodeName));
                boolean isRejectedByTaint = false;
                boolean isRejectedByMemory = false;
                boolean checkIncomplete = false;

                // a) Check Taints
                List<Taint> nodeTaints = Optional.ofNullable(node.getSpec().getTaints()).orElse(new ArrayList<>());
                if (!nodeTaints.isEmpty()) {
                     LOGGER.info(String.format("  Taints: %s", nodeTaints.stream()
                                                                 .map(t -> String.format("%s=%s:%s", t.getKey(), t.getValue(), t.getEffect()))
                                                                 .collect(Collectors.joining(", "))));
                    for (Taint taint : nodeTaints) {
                        if ("NoSchedule".equals(taint.getEffect()) || "NoExecute".equals(taint.getEffect())) {
                            if (!checkToleration(taint, podTolerations)) {
                                String reason = String.format("Untolerated taint '%s=%s:%s'", taint.getKey(), taint.getValue(), taint.getEffect());
                                rejectedByTaint.add(String.format("%s (%s)", nodeName, reason));
                                isRejectedByTaint = true;
                                break;
                            }
                        }
                    }
                } else {
                    LOGGER.info("  Taints: None");
                }

                if (isRejectedByTaint) {
                    LOGGER.info("  Result: Rejected due to taint.");
                    continue;
                }

                // b) Check Memory
                if (podMemoryRequestKib.compareTo(BigDecimal.ZERO) > 0) {
                    String allocatableMemoryStr = Optional.ofNullable(node.getStatus())
                                                          .map(NodeStatus::getAllocatable)
                                                          .map(m -> m.get("memory"))
                                                          .map(Quantity::toString)
                                                          .orElse("0");
                    BigDecimal allocatableMemoryKib = parseMemoryToKib(allocatableMemoryStr);
                    LOGGER.info(String.format("  Allocatable Memory: %s (%s KiB)", allocatableMemoryStr, allocatableMemoryKib.toBigInteger()));

                    BigDecimal allocatedMemoryRequestKib = BigDecimal.ZERO;
                    try {
                        String fieldSelector = String.format("spec.nodeName=%s,status.phase!=Failed,status.phase!=Succeeded", nodeName);
                        ListOptions listOptions = new ListOptionsBuilder().withFieldSelector(fieldSelector).build();
                        PodList nodePods = client.pods().inAnyNamespace().list(listOptions);

                        for (Pod npod : Optional.ofNullable(nodePods.getItems()).orElse(List.of())) {
                            if (npod.getSpec().getContainers() != null) {
                                for (Container container : npod.getSpec().getContainers()) {
                                    if (container.getResources() != null && container.getResources().getRequests() != null) {
                                        Quantity memReq = container.getResources().getRequests().get("memory");
                                        if (memReq != null) {
                                            allocatedMemoryRequestKib = allocatedMemoryRequestKib.add(parseMemoryToKib(memReq.toString()));
                                        }
                                    }
                                }
                            }
                        }
                        LOGGER.info(String.format("  Requested by Existing Pods: %s KiB", allocatedMemoryRequestKib.toBigInteger()));

                    } catch (KubernetesClientException e) {
                        String reason = String.format("API Error listing pods for memory calculation: %s", e.getMessage());
                        LOGGER.log(Level.WARNING, String.format("  Warning on node %s: %s", nodeName, reason), e);
                        nodesWithIssues.add(String.format("%s (%s)", nodeName, reason));
                        checkIncomplete = true;
                    } catch (Exception e) {
                         String reason = String.format("Error processing pods on node %s: %s", nodeName, e.getMessage());
                         LOGGER.log(Level.WARNING, String.format("  Warning: %s", reason), e);
                         nodesWithIssues.add(String.format("%s (%s)", nodeName, reason));
                         checkIncomplete = true;
                    }

                    if (!checkIncomplete) {
                        BigDecimal availableMemoryKib = allocatableMemoryKib.subtract(allocatedMemoryRequestKib);
                        LOGGER.info(String.format("  Available Memory (Allocatable - Requested): %s KiB", availableMemoryKib.toBigInteger()));

                        if (availableMemoryKib.compareTo(podMemoryRequestKib) < 0) {
                            String reason = String.format("Insufficient memory (Needs %s KiB, Available %s KiB)",
                                                          podMemoryRequestKib.toBigInteger(), availableMemoryKib.toBigInteger());
                            rejectedByMemory.add(String.format("%s (%s)", nodeName, reason));
                            isRejectedByMemory = true;
                            LOGGER.info("  Result: Rejected due to memory.");
                        }
                    } else {
                         LOGGER.info("  Result: Check Incomplete (due to pod listing error).");
                    }
                } // End memory check block

                // c) Final Node Status
                if (!isRejectedByTaint && !isRejectedByMemory && !checkIncomplete) {
                    availableNodesCount++;
                    LOGGER.info("  Result: Potentially Available.");
                } else if (checkIncomplete && !isRejectedByTaint) {
                     LOGGER.info("  Result: Check Incomplete.");
                }
            } // End node loop

            // --- 4. Summary ---
            // Use logger for summary without colors
            String summary = String.format(
                "%n--- Scheduling Check Summary ---%n" +
                "Pod: %s/%s%n" +
                "Memory Required (Largest Container): %s KiB%n" +
                "-".repeat(30) + "%n" +
                "Total Nodes Checked: %d%n" +
                "Nodes Rejected (Untolerated Taint): %d%n%s%n" +
                "Nodes Rejected (Insufficient Memory): %d%n%s%n" +
                "%s" +
                "%nPotentially Available Nodes (passed these checks): %d%n" +
                "%nDisclaimer: This script checks only taints/tolerations and memory requests.%n" +
                "Actual scheduling depends on other factors like node selectors, affinity, CPU, volumes, etc.",
                namespace, podName,
                podMemoryRequestKib.toBigInteger(),
                totalNodes,
                rejectedByTaint.size(),
                rejectedByTaint.isEmpty() ? "" : rejectedByTaint.stream().map(s -> "  - " + s).collect(Collectors.joining("\n")),
                rejectedByMemory.size(),
                rejectedByMemory.isEmpty() ? "" : rejectedByMemory.stream().map(s -> "  - " + s).collect(Collectors.joining("\n")),
                nodesWithIssues.isEmpty() ? "" : String.format("Nodes With Check Issues (e.g., API errors): %d%n%s%n",
                                                                nodesWithIssues.size(),
                                                                nodesWithIssues.stream().map(s -> "  - " + s).collect(Collectors.joining("\n"))),
                availableNodesCount
            );
            LOGGER.info(summary);


        } catch (KubernetesClientException e) {
            LOGGER.log(Level.SEVERE, "\nError: Kubernetes API interaction failed.", e);
            return 1;
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "\nAn unexpected error occurred.", e);
            // e.printStackTrace(); // Optionally keep for debugging unexpected errors
            return 1;
        }

        return 0; // Indicate success
    }

    // --- Main Method to run with Picocli ---
    public static void main(String... args) {
        // Ensure System.exit is called to pass the exit code back to the shell
        System.exit(new CommandLine(new CheckK8sNodeAvailability()).execute(args));
    }
}
